### ISSUE TITLE
Row grid fails in MS edge and MS Internet explorer 11

### ISSUE THREAD

**Issue by dotnetCarpenter** [Firefund/styleguide#109]
In #26, #90 the grid for the footer has a bug. The last row is pushed below the row.

**Comment by dotnetCarpenter** [comment]
This is a rounding error. If you change

``` css
from
.f-row_12 .f-row__cell-2 {
    ...
    width: calc(99.99% * 2/12 - 2.83333rem);
}
to
.f-row_12 .f-row__cell-2 {
    ...
    width: calc(99.9% * 2/12 - 2.83333rem);
}
```

then it works.
